:source-highlighter: highlightjs

= RoboCup Brazil 2026 SSL Robot Substitution
{docdate}
:toc:
:stem: latexmath
:sectnumlevels: 0

// add icons from fontawesome in a up-to-date version
ifdef::backend-html5[]
++++
<link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.3.1/css/all.css" integrity="sha384-mzrmE5qonljUremFsqc01SB46JvROS7bZs3IO2EmfFsd15uHvIt+Y8vEf7N7fWAU" crossorigin="anonymous">
++++
endif::backend-html5[]

:icons: font
:numbered:

NOTE: References to the male gender in the rules with respect to referees, team
members, officials, etc. are for simplification and apply to both males and
females.

== Goals of the Technical Challenge

In this challenge, the main goal is to test the ability of the team to perform a robot substitution without a field interview of the robot handler.

In specific game scenarios, as red cards and hardware issues, the robot handler needs to ask the referee for a robot substitution, leading to game stops and non dynamic matches. This challenge arises as an  incentive to teams to develop the skill of automatic substitution, where the robot places itself at a substitution area.

Aiming to establish a dynamic match that requires minimal human intervention, this challenge encourages innovation and continuous development in the SSL - Regular League.

=== Participation Requirements

All teams of the Regular League are eligible and *are encouraged* to participate in this challenge.

== Procedure

The evaluation of this technical challenge consists in two procedures: the first one adresses a red card situation, where the team acumulates successive faults and needs to remove one robot; the second one adresses the hardware issue situation, in this case, a low battery problem, where the robot needs to be subitituted due itself issue.

=== Robot substitution - red cards

This procedure consists in an automatic robot subistitution when a team gets a red card. First of all, the game controller and autoref must be set up as in normal match conditions. The teams are able to use not mor than 6 robots.


MULTIPLE_CARDS
TOO_MANY_ROBOTS
center line substitution area

=== Robot substitution - hardware issue

telemetry
low battery warning
encourage telemetry implemetation

=== Rules

center line substitution area
non changes at code during the atempt
no changes at firmware during the atempt


=== Scoring
red card - 1 point
low battery issue - 2 points
other hardware issue - 1 point



